# Header Menu
menu:
  Home: /
  Projects: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
  Contact: /contact/
  About: /about/
  Benfits: /benfits/
  Clubs: /clubs/
  Agendas & Minutes: /Agendas/
  Events: http://www.smc.edu/StudentServices/AssociatedStudents/Lists/Calendar/calendar.aspx
  


rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname:
google_analytics:
swiftype_install_key:

# Social
social:
  github: https://github.com/ptsteadman
  twitter: https://twitter.com/smc_as
  facebook: https://www.facebook.com/SMCAssociatedStudents
  rss: atom.xml
  linkedin: https://linkedin.com/in/ptsteadman
  stackoverflow: http://stackoverflow.com/users/2480493/patrick-steadman

# Miscellaneous
color_scheme: turquoise   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: AS-SMC # twitter username without the @
default_author: Anonymous

about: Computer Lab is a software development and marketing company based in Brooklyn, New York. <br><br> Computer Lab was founded in 2015, and is focused on so on and so forth.
phone: (310) 434-4250
email:
address_1: ​Student Life Office, Cayton Center
address_2: R​oom 202 (above the cafeteria)
address_3: 1900 Pico Boulevard, Santa Monica, CA 90405
skype: ptsteadman
lat: 34.016884
long: -118.469639
